# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'  # Use the sha / tag you want to point at
    hooks:
    - additional_dependencies: [types-python-dateutil==2.8.19]
      id: mypy
      pass_filenames: false
      files: ^bot/
      entry: bash -c 'mypy ./src/**/*.py'
      args: [
        "--ignore-missing-imports",
      ]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      args: [
        "--ignore=E203",
      ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: ["--line-length", "79"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--line-length", "79"]
-   repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
    - id: autoflake8
      args: [
        "--in-place",
        "--remove-unused-variables",
      ]
